config/routes.rb
Rails.application.routes.draw do

  resources :docxes do
    member do
      get "change/:change_id" , to: 'docxes#change',as: 'change', constraints: {change_id:  /[\d]*/}
      get 'download'
    end
  end
  mount Ckeditor::Engine => '/ckeditor'
  resources :images, :only=>[:new, :create,:show,:index]
  get 'intro/index'

  root 'images#new'

  resources :manuscripts do
    member do
      patch "docx"
      get 'download'
    end
  end

  
  
end

app/models/docx.rb
class Docx < ActiveRecord::Base

  has_many :docx_changes, :dependent =>  :destroy
  #has_many :changess, through: :docx_changes, class_name: "Change", foreign_key: :change_id

  has_attached_file :attachment#, :styles =>{:medium => '300x300>', :thumb => "100x100>"}, default_url: "/images/:style/missing.png"

  #after_create :unzip

  validates_attachment :attachment, :presence => true,
                       content_type:  { :content_type => ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"]}
  #:content_type => { :content_type => ["application/pdf"] ,
  #                    :message => ", #{I18n.t('activerecord.errors.models.manuscript.docx_content_type.invalid')}"}




  before_post_process on: :create do
    if attachment_content_type == 'application/octet-stream' || attachment_content_type == 'application/postscript'
      mime_type = MIME::Types.type_for(attachment_file_name)
      self.attachment_content_type = mime_type.first.to_s if mime_type.first
    end
  end

  def attachment?
    File.exists?(attachment.url(:change, false))
  end

  def zip_dir
    self.attachment.path.split("/")[0,self.attachment.path.split("/").count-2 ].join("/")
  end

  def unzip!
    dir  = zip_dir
    Dir.mkdir("#{dir}/unzip") unless File.exists?("#{dir}/unzip")
    system("unzip -d #{dir}/unzip #{attachment.path}")
  end

  def zip!
    dir  = zip_dir
    Dir.mkdir("#{dir}/change") unless File.exists?("#{dir}/change")
    system("cd #{dir}/unzip && zip -r ../change/#{self.attachment_file_name} *" );
  end


  def repair_wydle
    if attachment_content_type && (attachment_content_type.downcase=="application/octet-stream" || attachment_content_type.downcase=="application/postscript")
      hash = {"docx"=>"application/vnd.openxmlformats-officedocument.wordprocessingml.document" }
      last = attachment_file_name.downcase.split(".").last
      if ["docx"].include?(last)
        self.attachment_content_type = hash[last]
      else
        errors.add(:attachment_content_type, I18n.t('activerecord.errors.models.docx.attachment_content_type.invalid'))
      end
    end
  end
end

app/controllers/docx_controller.rb
class DocxController < ApplicationController

  require 'libreconv'
  #respond_to :docx

  def index
    #system "/usr/bin/soffice --headless --convert-to html --outdir /tmp /home/petule/work/karolinum/testy2/plan.docx"
    soubor = "Nemci"
    Libreconv.convert("#{Rails.root}/public/tests/#{soubor}.docx", "#{Rails.root}/public/tests/#{soubor}.html", nil, 'html')

    #html_doc =  File.open('/home/petule/work/karolinum/plan.html') { |f| Nokogiri::HTML(f)}

    #html_doc.search('//meta').each do |node|
    #node.remove if  ["changedby","created", "changed"].include? node['name']
    #end

    # File.write('/home/petule/work/karolinum/plankwok.html', html_doc.to_html)
    #Libreconv.convert('/home/petule/work/karolinum/plankwok.html', '/home/petule/work/karolinum/plankwok.docx', nil, 'docx')
    Libreconv.convert("#{Rails.root}/public/tests/#{soubor}.html", "#{Rails.root}/public/tests/#{soubor}_prevedeno.docx", nil, 'docx:"MS Word 2007 XML"')
   # Libreconv.convert("/tmp/#{soubor}.html", "#{Rails.root}/public/tests/#{soubor}_prevedeno.docx", nil, 'docx:"MS Word 2007 XML"')

  end



end

class String
	def string_between_markers marker1, marker2
		self[/#{Regexp.escape(marker1)}(.*?)#{Regexp.escape(marker2)}/m, 1]
	end
end

app/controllers/docxes_controller.rb
class DocxesController < ApplicationController
  before_action :set_docx, only: [:show, :edit, :update, :destroy]
  #after_action :destroy_docx, only: [:create]
  # GET /docxes
  # GET /docxes.json
  def index
    @docxes = Docx.all
  end

  # GET /docxes/1
  # GET /docxes/1.json
  def show

  end

  # GET /docxes/new
  def new
    @docx = Docx.new
  end

  def get_content txt
    t = txt.to_s.scan(/<w:t>(.*)<\/w:t>/).first
    if t.nil? || t.count==0
      #puts txt.to_s.scan(/<w:t xml:space="preserve">(.*)<\/w:t>/)
      txt.to_s.scan(/<w:t xml:space="preserve">(.*)<\/w:t>/).first
    else
      t
    end
  end

  # GET /docxes/1/edit
  def edit
  end

  # POST /docxes
  # POST /docxes.json
  def create
    @docx = Docx.new(docx_params)

    if  @docx.save
      @docx_load = @docx
      destroy_id = @docx_load.id
      @docx = Docx.new
      Thread.new do
        sleep 60*60*3 # platnost 3h
        destroy_docx = Docx.find destroy_id
        if destroy_docx
          dir_name = destroy_docx.zip_dir
          destroy_docx.destroy
          FileUtils.remove_dir(dir_name)
        end
      end
    end

  end

  def change
    @change = DocxChange.find params[:change_id]
    @change.apply!
    @change.used!
    @next_change = @change.docx.docx_changes.by_unused.first
    if @next_change.nil?
      @change.docx.zip!
      respond_to do |format|
        format.js{redirect_to download_docx_path(@change.docx)}
      end
    end
  end


  def download
    @docx = Docx.find params[:id]
    Thread.new do
      sleep 55
      dir_name = @change.docx.zip_dir
      @change.docx.destroy
      FileUtils.remove_dir(dir_name)
    end
  end

  # PATCH/PUT /docxes/1
  # PATCH/PUT /docxes/1.json
  def update
    @docx_load = Docx.find params[:id]
    @changes = params[:docx][:changes] if params[:docx]
    if @changes
      @changes.each do |change|
        DocxChange.create(:change_id => change, :docx_id => @docx_load.id)
      end
      @docx.unzip!
    end
  end

  # DELETE /docxes/1
  # DELETE /docxes/1.json
  def destroy
    @docx.destroy
    respond_to do |format|
      format.html { redirect_to docxes_url, notice: 'Docx was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docx
      @docx = Docx.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docx_params
      params.require(:docx).permit( :attachment )
    end

  def destroy_docx
    @docx.destroy if @docx
  end
end

app/views/docxes/_changes_form.html.erb
<%docx = (@docx_load ? @docx_load : @docx)%>
<% err = docx.errors.any?%>

<%= form_for(docx, html: { multipart: true,class: "form-inline" }, :remote => true) do |f| %>

    <div class="form-group margin-top-20">
      <h3><%=t 'app.change.title'%></h3>
    </div>
    <div class="cl"></div>
    <%if docx.id.nil? %>
        <i><%=t 'app.docx.changes_info'%></i>
    <%else%>
        <%= f.submit t('app.docx.change'), :class=>"btn btn-danger float-left", :id=>"change_btn", :disabled=>"disabled" %>
        <div class="ajax-load" id="ajax-changing"><%=t('app.change.running')%></div>
    <% end %>
    <div class="cl"></div>
    <div class="form-group margin-top-20">
      <div class="panel panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">
            <div class="checkbox">
            <label>
              <input type="checkbox" id="change-all" <%=(docx.id.nil? && !err) ? "disabled" : "" %> >&nbsp;<%=t 'app.change.all'%>
            </label>
          </div></h3>
        </div>
        <div class="panel-body">
          <%Change.obj_parents.each do |change| %>
              <div class="checkbox block-checkbox">
                <label id="label-change-<%=change.id%>">
                  <input type="checkbox" <%=(docx.id.nil? && !err) ? "disabled" : "" %> name="docx[changes][]" value="<%=change.id%>" id="change-<%=change.id%>" data-id="<%=change.id%>" class="chxb <%=change.parent? ? "parent" : ""%>" >&nbsp;<%=change.to_s%>
                </label>
                <div class="ajax-load" id="ajax-<%=change.id%>"><%=t('app.docx.new.changing')%></div>
                &nbsp;<div id="ajax-status-change-<%=change.id%>" class="load-status"></div>
                <%change.childrens.each do |child|%>
                    <div class="checkbox block-checkbox child-checkbox">
                      <label id="label-change-<%=child.id%>">
                        <input type="checkbox" name="docx[changes][]" value="<%=child.id%>" id="change-<%=child.id%>" class="children chxb parent-<%=change.id%>" disabled>&nbsp;<%=child.to_s%>
                      </label>
                      <div class="ajax-load" id="ajax-<%=child.id%>"><%=t('app.docx.new.changing')%></div>
                      &nbsp;<div id="ajax-status-change-<%=child.id%>" class="load-status"></div>
                    </div>
                    <div class="cl"></div>
                <% end %>
              </div>
              <div class="cl"></div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="cl"></div>
<% end %>

app/views/docxes/_form.html.erb
<h1 class="newdoc"><%= t 'app.docx.new.title' %></h1>
<h1 class="changedocx"><%= t 'app.docx.edit.title' %></h1>
<%=link_to t('app.docx.new.btn'), new_docx_path, :class=>"btn btn-warning" , :id=>"new-docx-btn" %>
<%= form_for(@docx, html: { multipart: true,class: "form-inline" }, :remote => true) do |f| %>
    <%= render :partial => 'others/form_errors_attachment', :locals => {:object => f.object, :attachment=>"attachment"} %>
    <div class="form-group">
      <%= f.file_field :attachment, :class=>"form-control", :required=>true %>
    </div>

    <div class="form-group">
      <%= f.submit t('app.docx.new.submit'), :class=>"btn btn-warning" %>
      <div id="ajax-load"><%=t('app.docx.new.loading')%></div>
      <div id="ajax-status-attachment" class="load-status"></div>
    </div>
    <div class="cl"></div>
    <div class=" margin-top-20" id="download-link"></div>
    <div class="cl"></div>
    <div class=" margin-top-20" id="load-statuses"></div>

    <div class="cl"></div>
<% end %>

app/views/docxes/change.js.erb
<% if !@change.nil? and @change.errors.any? %>
    $("#load-statuses").append("<%= escape_javascript(  render :partial => 'docxes/statuses/box_status', :locals =>
        {:error=>true, :title=>@change.to_s, :text=> @change.errors.map{|err| err.to_s}.join(", ")} ) %>")
<% else
    if @next_change %>
        changes("<%=change_docx_path(@change.docx, @next_change.id)%>", "<%=@next_change.id%>")

<%  end %>
    $("#ajax-<%=@change.id%>").hide("slowly")
    var txt = "<%= escape_javascript(  render :partial => 'docxes/statuses/status' , :locals => {error: nil}) %>";
    $("#ajax-status-change-<%=@change.change.id%>").html(txt)
    $("#label-change-<%=@change.change.id%>").addClass("status alert-success")
    $("#change_btn").attr('disabled', true);
<% end %>


load()

app/views/docxes/create.js.erb
<% if !@docx.nil? and @docx.errors.any? %>

    var content = "<%= escape_javascript(  render :partial => 'docxes/form' ) %>";
    $("#new-form").html(content)
    var content_edit = "<%= escape_javascript(  render :partial => 'docxes/changes_form' ) %>";
    $("#edit-form").html(content_edit)
<%elsif @changes.nil? || @changes.count==0%>

    var content = "<%= escape_javascript(  render :partial => 'docxes/form' ) %>";
    $("#new-form").html(content)
    $("#load-statuses").append("<%= escape_javascript(  render :partial => 'docxes/statuses/box_status', :locals =>
        {:error=>false, :title=>t('app.docx.status.attachment.title'), :text=>t('app.docx.status.attachment.ok')} ) %>")
    var content_edit = "<%= escape_javascript(  render :partial => 'docxes/changes_form' ) %>";
    $("#edit-form").html(content_edit)
<%else%>
    $("#new_docx .alert-danger").remove();
    $("#ajax-load").hide("slowly")
    var txt = "<%= escape_javascript(  render :partial => 'docxes/statuses/status' , :locals => {error: nil}) %>";
    $("#ajax-status-attachment").html(txt)
    $("#load-statuses").append("<%= escape_javascript(  render :partial => 'docxes/statuses/box_status', :locals =>
        {:error=>false, :title=>t('app.docx.status.attachment.title'), :text=>t('app.docx.status.attachment.ok')} ) %>")
    //spusteni uprav
    <% change = @docx_load.docx_changes.by_unused.first%>
    changes("<%=change_docx_path(@docx_load, change.id)%>", "<%=change.id%>")
<%end %>
//alert("<%=@changes ? @changes.join(",") : ""%>")
//if ()
load()

app/views/docxes/download.js.erb
<% if @docx.attachment?%>
    $( "#load-statuses" ).after( "<div class='alert alert-danger' role='alert'> <strong><%=t 'app.docx.zip-error-title'%></strong> <%=t 'app.docx.zip-error'%></div>" );

<% else %>
    $("#load-statuses div").append('<br /><strong><%=t 'app.change.title' %>:</strong> <%=t('app.docx.status.changes.allok')%>')
    $("#download-link").html("<%= escape_javascript(  render :partial => 'docxes/statuses/download', :locals =>{:docx=>@docx} ) %>")
    var act_time = new Date().getTime();
    show_time();
<% end %>
$("input[type='checkbox']").attr("disabled", true)
$("#ajax-changing").hide()
load()

app/views/docxes/edit.html.erb
<h1>Editing Docx</h1>

<%= render 'form' %>

<%= link_to 'Show', @docx %> |
<%= link_to 'Back', docxes_path %>

app/views/docxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Docxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docxes.each do |docx| %>
      <tr>
        <td><%= link_to 'Show', docx %></td>
        <td><%= link_to 'Edit', edit_docx_path(docx) %></td>
        <td><%= link_to 'Destroy', docx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Docx', new_docx_path %>

app/views/docxes/new.html.erb
<div class="row">

  <div id="new-form">
    <%= render 'form' %>
  </div>
  <div id="edit-form">
    <%= render 'changes_form' %>
  </div>
</div>
<div class="cl"></div>

app/views/docxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_docx_path(@docx) %> |
<%= link_to 'Back', docxes_path %>

app/views/docxes/update.js.erb
    $("#new_docx .alert-danger").remove();
    $("#ajax-load").hide("slowly")
    var txt = "<%= escape_javascript(  render :partial => 'docxes/statuses/status' , :locals => {error: nil}) %>";
    $("#ajax-status-attachment").html(txt)

    //spusteni uprav
    <% change = @docx_load.docx_changes.by_unused.first%>
    changes("<%=change_docx_path(@docx_load, change.id)%>", "<%=change.id%>")


load()