config/routes.rb
Rails.application.routes.draw do

  resources :docxes do
    member do
      get "change/:change_id" , to: 'docxes#change',as: 'change', constraints: {change_id:  /[\d]*/}
      get 'download'
    end
  end
  mount Ckeditor::Engine => '/ckeditor'
  resources :images, :only=>[:new, :create,:show,:index]
  get 'intro/index'

  root 'images#new'

  resources :manuscripts do
    member do
      patch "docx"
      get 'download'
    end
  end

  
  
end

app/models/manuscript.rb
class Manuscript < ActiveRecord::Base
  require 'libreconv'
  has_attached_file :docx#, :styles =>{:medium => '300x300>', :thumb => "100x100>"}, default_url: "/images/:style/missing.png"

  #after_create :convert_to_html

  validates_attachment :docx, :presence => true,
                       content_type:  { :content_type => ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"]}
                       #:content_type => { :content_type => ["application/pdf"] ,
                      #                    :message => ", #{I18n.t('activerecord.errors.models.manuscript.docx_content_type.invalid')}"}

  

  
  before_post_process on: :create do
    if docx_content_type == 'application/octet-stream' || docx_content_type == 'application/postscript'
      mime_type = MIME::Types.type_for(docx_file_name)
      self.docx_content_type = mime_type.first.to_s if mime_type.first
    end
  end
  

  def

  
  def repair_wydle    
    if docx_content_type && (docx_content_type.downcase=="application/octet-stream" || docx_content_type.downcase=="application/postscript")
      hash = {"docx"=>"application/vnd.openxmlformats-officedocument.wordprocessingml.document" }
      last = docx_file_name.downcase.split(".").last
      if ["docx"].include?(last)
        self.docx_content_type = hash[last]
      else
        errors.add(:docx_content_type, I18n.t('activerecord.errors.models.manuscript.docx_content_type.invalid'))
      end      
    end
  end

  def convert_to_html
    file_arr = docx.path.split(".")
    file = "#{file_arr[0,file_arr.count-1].join(".")}.html"
    Libreconv.convert(docx.path, file, nil, 'html')
    html_doc =  File.open(file) { |f| Nokogiri::HTML(f)}
    self.html = html_doc.to_html
    #self.html = File.open(file, 'rb') { |f| f.read }
    self.save
  end

  def self.docx name, html
    name = name.split(".")[0]
    uniq = Time.now.to_i
    dir = "#{Rails.root}/public/#{uniq}"
    Dir.mkdir(dir) unless File.exists?(dir)
    File.open("#{dir}/#{name}.html", "w") { |file| file.write html}
    Libreconv.convert("#{dir}/#{name}.html", "#{dir}/#{name}.docx", nil, 'docx:"MS Word 2007 XML"')
    "#{uniq}/#{name}.docx"

  end

  private

# Retrieves dimensions for image assets
# @note Do this after resize operations to account for auto-orientation.



  
end

app/controllers/manuscripts_controller.rb
class ManuscriptsController < ApplicationController

  before_action :set_manuscript, only: [:destroy]
  #after_action :destroy_manuscript, only: [:create]

  def create
    @manuscript = Manuscript.new(manuscript_params)
    respond_to do |format|
      if @manuscript.save
        @manuscript.convert_to_html
        format.html { redirect_to @manuscript, notice: t('app.manuscript.created') }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def show
    begin
      @manuscript_load = Manuscript.find(params[:id])
      @manuscript = Manuscript.new
    rescue Exception => e
      respond_to do |format|
        format.html { redirect_to new_manuscript_path, notice: t('app.manuscript.no-exists') }
      end
    end


  end

  def new
    @manuscript = Manuscript.new
  end

  def index
    #system "/usr/bin/soffice --headless --convert-to html --outdir /tmp /home/petule/work/karolinum/testy2/plan.docx"
    soubor = "Nemci"
    Libreconv.convert("#{Rails.root}/public/tests/#{soubor}.docx", "#{Rails.root}/public/tests/#{soubor}.html", nil, 'html')

    #html_doc =  File.open('/home/petule/work/karolinum/plan.html') { |f| Nokogiri::HTML(f)}

    #html_doc.search('//meta').each do |node|
    #node.remove if  ["changedby","created", "changed"].include? node['name']
    #end

    # File.write('/home/petule/work/karolinum/plankwok.html', html_doc.to_html)
    #Libreconv.convert('/home/petule/work/karolinum/plankwok.html', '/home/petule/work/karolinum/plankwok.docx', nil, 'docx')
    Libreconv.convert("#{Rails.root}/public/tests/#{soubor}.html", "#{Rails.root}/public/tests/#{soubor}_prevedeno.docx", nil, 'docx:"MS Word 2007 XML"')
    # Libreconv.convert("/tmp/#{soubor}.html", "#{Rails.root}/public/tests/#{soubor}_prevedeno.docx", nil, 'docx:"MS Word 2007 XML"')

  end

  def download
    manuscript = Manuscript.find(params[:id])
    cookies['fileDownload'] = 'true'
    file = "#{Rails.root}/public/#{params[:file]}"
    send_file file,
              filename: manuscript.docx_file_name,
              type: manuscript.docx_content_type,
              x_sendfile: true


    Thread.new do
      sleep 3
      manuscript.destroy
      file_arr = file.split("/")
      FileUtils.remove_dir  file_arr[0,file_arr.count-1].join("/")
    end
  end


  def docx
    parm = manuscript_docx_params
    begin
      file = Manuscript.docx parm[:docx_file_name], parm[:html]
    rescue Exception => e
      Rails.logger.debug e.backtrace
      @error = true
    end
    @error = !File.exists?("#{Rails.root}/public/#{file}")
    @file = file

#
  end
  private



  def set_manuscript
    @manuscript_load = Manuscript.find(params[:id])
  end

  def manuscript_docx_params
    params.require(:manuscript).permit( :docx_file_name, :html, :docx_content_type)
  end

  def manuscript_params
    params.require(:manuscript).permit( :docx, :html)
  end

  def destroy_manuscript
    @manuscript_load.destroy if @manuscript_load
  end
end

app/views/manuscripts/_form.html.erb
<%= form_for(@manuscript, html: { multipart: true,class: "form-inline" }) do |f| %>
  <%= render :partial => 'others/form_errors_attachment', :locals => {:object => f.object, :attachment=>"docx"} %>
  <div class="form-group">
    <%= f.file_field :docx, :class=>"form-control", :required=>true %>
  </div>
 
  <div class="form-group">
    <%= f.submit t('app.manuscript.new.submit'), :class=>"btn btn-warning" %>
    <div id="ajax-load"><%=t('app.manuscript.new.loading')%></div>
  </div>
<% end %>

app/views/manuscripts/_form_html.html.erb
<%= form_for(@manuscript_load, :url=> docx_manuscript_path(@manuscript_load), :remote => true) do |f| %>
  <%#= render :partial => 'others/form_errors_attachment', :locals => {:object => f.object, :attachment=>"docx"} %>
  <div class="form-group">
        <%=button_tag :type=>"submit",  :class=>"btn btn-primary btn-download" do %>
            <%=t('app.manuscript.show.docx')%>&nbsp;<i class='fa fa-download'></i>
        <% end %>
      <div id="ajax-download-div">
        <div id="ajax-download"><%=t('app.manuscript.show.downloading')%></div>
        <div class="cl"></div>
      </div>
  </div>
    <div class="form-group">
      <strong><%= t 'activerecord.attributes.manuscript.docx_file_name'%>: </strong>
      <%=@manuscript_load.docx_file_name%>
      <%=f.hidden_field :docx_file_name%>
      <%=f.hidden_field :docx_content_type%>
    </div>
    <div class="form-group">
      <%= f.label :html %>
      <%= f.cktext_area :html, :rows=>50,:class=>"form-control", :ckeditor => {:language => 'cs'}%>
    </div>

<% end %>

app/views/manuscripts/_new.html.erb
<div class="row">
    <h1><%= t 'app.manuscript.new.title' %></h1>
    <div id="new-form">
    <%= render 'form' %>
    </div>
</div>

app/views/manuscripts/_show.html.erb
<%= cktext_area_tag "notes", @manuscript.html, :class => 'someclass', :ckeditor => {:language => 'cs'} %>

app/views/manuscripts/create.js.erb
var content = "<%= escape_javascript(  render :partial => 'manuscripts/form' ) %>";

$("#new-form").html(content);
<% if @manuscript_load %>
content_show = "<%#= escape_javascript(  render :partial => 'manuscripts/show' ) %>";

$("#show-manuscript").html("tests<%=@html%>");
<% else  %>
$("#show-manuscript").html("nic...");
<%end %>
load_manuscript()

app/views/manuscripts/docx.js.erb
<% if @error%>
show_error("<%=t('app.manuscript.show.download_error') %>")
$(".btn-download").show("slowly")
$("#ajax-download-div").hide("slowly")
<% else %>
//show_error("<%=t('app.manuscript.show.download_error') %>")
//$(".progress-label").html("<%= t 'drm.title-load' %>")

$.fileDownload('<%=download_manuscript_path(params[:id], :file=> @file)%>', {
    successCallback: function (url) { $("#manuscripts-form").html("") },
    failCallback: function (url) {
        console.log(url)
        show_error("<%= t 'app.manuscript.show.download_error' %>") }
});
<% end %>

app/views/manuscripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.token %></td>
        <td><%= image.download %></td>
        <td><%= link_to 'Show', image %></td>
        
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/manuscripts/new.html.erb
<%= render 'new' %>

<% if @download%>
<script type="text/javascript">
    $.fileDownload('<%=download_download_path(params[:code],params[:link])%>', {
        successCallback: function (url) {$('#downloaddiv').dialog('close'); },
        failCallback: function (url) {
            console.log(url)
        show_error("<%= t 'drm.download-error' %>") }
        });
</script>
<% end %>
   <div id="show-manuscript">
  <%#= cktext_area_tag "notes", Manuscript.last.html, :class => 'someclass', :ckeditor => {:language => 'cs'} %>
</div>

app/views/manuscripts/show.html.erb
<%= render 'new' %>
<div class="row  margin-top-20">
  <% if @error%>
    <div class="alert alert-danger alert-dismissable">
      <i class="fa fa-ban"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= t 'app.manuscript.show.download_error'%>
    </div>
  <% end %>
</div>
<div class="row margin-top-20" id="manuscripts-form"><%=render :partial => 'manuscripts/form_html' %></div>
<div class="clear"></div>