config/routes.rb
Rails.application.routes.draw do

  resources :docxes do
    member do
      get "change/:change_id" , to: 'docxes#change',as: 'change', constraints: {change_id:  /[\d]*/}
      get 'download'
    end
  end
  mount Ckeditor::Engine => '/ckeditor'
  resources :images, :only=>[:new, :create,:show,:index]
  get 'intro/index'

  root 'images#new'

  resources :manuscripts do
    member do
      patch "docx"
      get 'download'
    end
  end

  
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  require 'rmagick'
  
  has_attached_file :image, :styles =>{:medium => '300x300>', :thumb => "100x100>"}, default_url: "/images/:style/missing.png"
  
  

  validates_attachment :image, :presence => true,
    :content_type => { :content_type => ["application/pdf", /\Aimage\/.*\Z/,
    "application/illustrator","image/x-eps","application/octet-stream", "application/postscript"] ,
    :message => ", #{I18n.t('activerecord.errors.models.image.image_content_type.invalid')}"}
  
  validate :repair_wydle
  
  before_save :extract_dimensions, :set_token
  serialize :dimensions  
  
  #(rozměr x / 300) * 2,54 = výsledek pro osu x
  def dpi_cm
    width, height = dimensions
    return ((((width.to_f / 300) * 2.54).to_f).round(2)), (((height.to_f / 300) * 2.54).to_f.round(2))
    
  end
  
  before_post_process on: :create do    
    if image_content_type == 'application/octet-stream' || image_content_type == 'application/postscript'
      mime_type = MIME::Types.type_for(image_file_name) 
      self.image_content_type = mime_type.first.to_s if mime_type.first  
    end
  end
  
  def dpi
    img = Magick::Image.read(image.path)[0]
    #width = img.columns
   #height = img.rows
    #puts " UMISTENI #{image.path} #{img.x_resolution} #{img.units}  #{width} #{height}"
    #width, height = dimensions
    #d = (width.to_f^2 + height.to_f^2)^0,5
    #return (width.to_f^2 + height.to_f^2)^0,5 / d 
    #puts "IMAGE_DPI #{img.columns} x #{img.rows}"
    return img.x_resolution && img.x_resolution.to_i>0 ? img.x_resolution : 72
  end
  
  def image?
    ["image/png","image/tiff","image/jpeg","image/jpg"].include?(image_content_type.downcase)
  end
  
  def allowed_vector?
    ["application/illustrator","image/x-eps","application/pdf"].include?(image_content_type.downcase)
  end
  
  def vector?
    ["application/illustrator","image/x-eps", "image/vnd.adobe.photoshop", "image/svg+xml", "application/pdf"].include?(image_content_type.downcase)
  end
  
  def pdf?
    image_content_type.downcase=="application/pdf"
  end
 
  
  def repair_wydle    
    if image_content_type && (image_content_type.downcase=="application/octet-stream" || image_content_type.downcase=="application/postscript")
      hash = {"ai"=>"application/illustrator", "eps" => "image/x-eps", 
        "pdf"=>"application/pdf", "svg"=>"image/svg+xml", "psd"=>"image/vnd.adobe.photoshop" }
      last = image_file_name.downcase.split(".").last
      if ["ai","eps","pdf", "svg", "psd"].include?(last)
        self.image_content_type = hash[last]
      else
        errors.add(:image_content_type, I18n.t('activerecord.errors.models.image.image_content_type.invalid'))
      end      
    end
  end
  
  private

# Retrieves dimensions for image assets
# @note Do this after resize operations to account for auto-orientation.
  def extract_dimensions  
    tempfile = image.queued_for_write[:original]
    unless tempfile.nil?
      geometry = Paperclip::Geometry.from_file(tempfile)
      puts" geo #{geometry} #{tempfile}"
      self.dimensions = [geometry.width.to_i, geometry.height.to_i]
    end
  end
  
  def set_token
    self.token = SecureRandom.urlsafe_base64
  end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :set_image, only: [:show, :destroy]
  after_action :destroy_image, only: [:create]
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    if @image.save
      @image_load = @image
      @image = Image.new      
    end
    #respond_to do |format|
    #  if @image.save
    #    format.html { redirect_to @image, notice: 'Image was successfully created.' }
    #    format.json { render :show, status: :created, location: @image }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @image.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image_load = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:token, :download, :image)
    end
    
    def destroy_image
      @image_load.destroy if @image_load
    end
end

app/helpers/images_helper.rb
module ImagesHelper
  def row_format image
    #if image.vector?
    #  "warning"
    #elsif !image.image? 
    #  "danger"
      
    #end
    if image.allowed_vector? || image.image? 
      "success"
    else
      "danger"
    end
  end
  
  def dimension image
    width, height = image.dimensions
    "#{width}px / #{height}px"    
  end
  
  def dpi_cm image
    width, height = image.dpi_cm
    "#{width}cm / #{height}cm"       
  end
  
  def image_type image
    type = image.image_content_type.split("/").reverse.first
    #if image.pdf?
   #   info = t('app.image.show.comments.pdf')
    #elsif image.allowed_vector?
    #  info = t('app.image.show.comments.vector_ok')
    #elsif  image.vector?
    #  info = t('app.image.show.comments.vector_ko')
    #elsif  image.image?
    #  info = t('app.image.show.comments.image_ok')
    #else
    #  info = t('app.image.show.comments.image_ko')
    #end
    #"<p class='typ'>#{type}</p><p class='info'>#{info}</p>"
    type
  end

  def image_note image
    type = image.image_content_type.split("/").reverse.first
    if image.pdf?
      info = t('app.image.show.comments.pdf')
    elsif image.allowed_vector?
      info = t('app.image.show.comments.vector_ok')
    elsif  image.vector?
      info = t('app.image.show.comments.vector_ko')
    elsif  image.image?
      info = t('app.image.show.comments.image_ok')
    else
      info = t('app.image.show.comments.image_ko')
    end
    info
  end
end

app/views/images/_form.html.erb
<%= form_for(@image, html: { multipart: true,class: "form-inline" }, :remote => true) do |f| %>
<% #width, height = @image.dimensions%>
<%#="#{width}|#{height}"%>

  <% if @image.errors.any? %>
   <%#=@image.image_content_type%>
   <%=puts "KWOK #{@image.errors}"%>
    <%
    errors = Array.new
    @image.errors.each do |message|        
      errors << message.to_s 
     end %>
    <%if errors.include?("image_content_type") || errors.include?("image")%>
      <div id="error_explanation">      
        <ul class="errorslist">             
          <li class="text-danger"><i class="fa fa-times text-danger"></i> <%= t 'app.image.show.custom_error' %></li>      
        </ul>      
      </div>
    <%else%>
      <div id="error_explanation">
      <% count = @image.errors.count %>
      <h4 class="text-danger"><%=count%> <%=t("errors.template.header.error#{(count>1 && count<5) ? "_less" : (count>5 ? "s": "")  }" ) %><%=t('errors.template.header.image')%>:</h4>
            
      <ul class="errorslist">
        <% @image.errors.full_messages.each do |message| %>        
          <li><i class="fa fa-times text-danger"></i> <%= message %></li>
      <% end %>
      </ul>
      </div>
    <% end %>  
  <% end %>

  <div class="form-group">
    <%= f.file_field :image, :class=>"form-control", :required=>true %>
  </div>
 
  <div class="form-group">
    <%= f.submit t('app.image.new.submit'), :class=>"btn btn-warning" %>
    <div id="ajax-load"><%=t('app.image.new.loading')%></div>
  </div>
<% end %>

app/views/images/_show.html.erb
<table class="table table-hover margin-top-20 margin-bottom-20">
  <tr class="info">
    <th scrope="row" ><%=t 'app.image.show.name'%></th>
    <td>
      <%=@image_load.image_file_name%>
    </td>    
  </tr>
  <tr class="<%=row_format(@image_load)%>">
    <th scrope="row" ><%=t 'app.image.show.content_type'%></th>
    <td>
      <%=image_type @image_load%>     
    </td>    
  </tr>
  <tr class="<%=row_format(@image_load)%>">
    <th scrope="row"><%=t 'app.image.show.note'%></th>
    <td><%=image_note @image_load%> </td>
  </tr>
  <% if @image_load.vector? %>
    <tr>
      <th scrope="row"><%=t 'app.image.show.px'%></th>
      <td>—</td>
    </tr>
    <tr>
      <th scrope="row"><%=t 'app.image.show.dpi'%></th>
      <td><%="—, <strong>#{t('app.image.show.vector')}</strong>"%></td>
    </tr>
    <tr>
      <th scrope="row"><%=t 'app.image.show.dpi_cm'%></th>
      <td>—</td>
    </tr>
  <%else%>
    <tr>
      <th scrope="row"><%=t 'app.image.show.px'%></th>
      <td><%=dimension(@image_load)%></td>
    </tr>
    <tr>
      <th scrope="row"><%=t 'app.image.show.dpi'%></th>
      <td><%=@image_load.dpi%></td>
      <%#=@image_load.dpi%><%#= ", <strong>#{t('app.image.show.vector')}</strong>".html_safe if @image_load.vector? %>
    </tr>
    <tr>
      <th scrope="row"><%=t 'app.image.show.dpi_cm'%></th>
      <td><%=dpi_cm(@image_load)%></td>
    </tr>
  <%end%>
  <%# if !@image_load.vector? %>
    
  <% #end %>   
</table>
<div ><%#= image_tag @image_load.image.url %></div>

app/views/images/create.js.erb
var content = "<%= escape_javascript(  render :partial => 'images/form' ) %>";
$("#new-form").html(content);
<% if @image_load %>
  content = "<%= escape_javascript(  render :partial => 'images/show' ) %>";
  $("#show-image").html(content);
 <% else  %> 
  $("#show-image").html("");
<%end %>
  load( )

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.token %></td>
        <td><%= image.download %></td>
        <td><%= link_to 'Show', image %></td>
        
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1><%= t 'app.image.new.title' %></h1>
<div id="new-form">
  <%= render 'form' %>
</div>
<div id="show-image">
  
</div>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @image.token %>
</p>

<p>
  <strong>Download:</strong>
  <%= @image.download %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>